#CONTADORES
#TABLA VOTO
SELECT COUNT(*) FROM voto;

#TABLA PARTIDO
SELECT COUNT(*) FROM partido;

#TABLA MUNICIPIO
SELECT COUNT(*) FROM (
	SELECT DISTINCT nombre
	FROM municipio
) as n;
SELECT COUNT(*) FROM zona;

#TABLA DEPARTAMENTO
SELECT COUNT(*) FROM (
	SELECT DISTINCT nombre
	FROM depto
) as n;
SELECT COUNT(*) FROM depto;

#TABLA REGION
SELECT COUNT(*) FROM (
	SELECT DISTINCT (CAST(nombre AS CHAR CHARACTER SET utf8) COLLATE utf8_bin)
	FROM region
) as n;

#TABLA PAIS
SELECT COUNT(*) FROM pais;

#TABLA ELECCION
SELECT COUNT(*) FROM eleccion;

#TABLA RAZA
SELECT COUNT(*) FROM raza;
