/*Creacion de Tabla Temporal */
CREATE TEMPORARY TABLE IF NOT EXISTS temporal (
	NOMBRE_ELECCION	VARCHAR(200),
	ANIO_ELECCION VARCHAR(200),
	PAIS VARCHAR(200),
	REGION VARCHAR(200),
	DEPTO VARCHAR(200),
	MUNICIPIO VARCHAR(200),
	PARTIDO VARCHAR(200),
	NOMBRE_PARTIDO VARCHAR(200),
	SEXO VARCHAR(200),
	RAZA VARCHAR(200),
	ANALFABETOS VARCHAR(200),
	ALFABETOS VARCHAR(200),
	PRIMARIA VARCHAR(200),
	NIVEL_MEDIO VARCHAR(200),
	UNIVERSITARIOS VARCHAR(200)
);
/* Carga de Datos */