/*Creacion de Tabla Temporal */
CREATE TEMPORARY TABLE IF NOT EXISTS temporal (
	NOMBRE_ELECCION	VARCHAR(200),
	ANIO_ELECCION VARCHAR(200),
	PAIS VARCHAR(200),
	REGION VARCHAR(200),
	DEPTO VARCHAR(200),
	MUNICIPIO VARCHAR(200),
	PARTIDO VARCHAR(200),
	NOMBRE_PARTIDO VARCHAR(200),
	SEXO VARCHAR(200),
	RAZA VARCHAR(200),
	ANALFABETOS VARCHAR(200),
	ALFABETOS VARCHAR(200),
	PRIMARIA VARCHAR(200),
	NIVEL_MEDIO VARCHAR(200),
	UNIVERSITARIOS VARCHAR(200)
);

/* Carga de Datos */
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/ICE_Fuente.csv'
INTO TABLE temporal
FIELDS TERMINATED BY ';' ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(
	NOMBRE_ELECCION,
	ANIO_ELECCION,
	PAIS,
	REGION,
	DEPTO,
	MUNICIPIO,
	PARTIDO,
	NOMBRE_PARTIDO,
	SEXO,
	RAZA,
	ANALFABETOS,
	ALFABETOS,
	PRIMARIA,
	NIVEL_MEDIO,
	UNIVERSITARIOS 
);
